Lesson 7/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

Lesson 7/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

Lesson 7/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='list'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

Lesson 7/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import urls
from . import settings
from .views import contacts, main

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

Lesson 7/mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

Lesson 7/geekshop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def main(request):
    products = Product.objects.all()[:4]
    basket = ''
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    context = {
        'description': 'Офигенские СТУЛЬЯ',
        'subject': 'Популярно в лучших домах Филадельфии',
        'products': products,
        'basket': basket,
    }
    return render(request, 'index.html', context=context)


def contacts(request):
    return render(request, 'contact.html')

Lesson 7/geekshop/templates/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="index.html" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="{% if request.resolver_match.kwargs.route == '' %}
                    active
                  {% endif %}">домой</a></li>
        <li><a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.route == 'products/' %}
                    active
                  {% endif %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}" class="{% if request.resolver_match.route == 'contacts/' %}
                    active
                  {% endif %}">контакты</a></li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' %}">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
            </li>
        {% endif %}

    {% if user.is_superuser %}
                <li>
            <a href="{% url 'admin_staff:users' %}">
                    админка
            </a>
        </li>
    {% endif %}
            <li>
                  <a href="{% url 'order:list' %}">заказы</a>
                {% if user.is_authenticated %}
                  <a href="{% url 'auth:logout' %}">выйти</a>
                {% else %}
                  <a href="{% url 'auth:login' %}">войти</a>
                {% endif %}
            </li>
    </ul>
{% if basket %}
    <a href="{% url 'basket:list' %}" class="fa fa-shopping-basket">
        <span>
            {{ basket.0.total_cost|floatformat:0 }} руб.
            ({{ basket.0.total_quantity }} шт.)
        </span>
    </a>
{% endif %}
    <a href="#" class="search"></a>
</div>